### ISSUE TITLE
Handle the `IntentedFor`

### ISSUE THREAD

**Issue by mirestrepo** [brown-bnc/xnat-tools#19]
Handle the `IntentedFor` field in the `json` file for the field map.

For now it can be manually added, but it would be nice to handle it using Heudiconv or as a post processing step

**Comment by debyee** [comment]
I just contacted the fMRIprep folks to ask about this. Looks like they are not planning to implement this in fMRIprep for the time being, so they suggest just manually adding, because there is a lot of diversity in how the fieldmap should be applied in fMRI data analysis. 

It could be nice to handle it as a post-processing step, but this may only be useful if others generally use the fieldmap like we do -- and they apply the fieldmap to all of the functional runs for fieldmap correction (I can't exactly predict how others use field maps, so it could be useful to survey others for their preferences?). 

Reference to issue: https://github.com/nipreps/sdcflows/issues/66
